version: '3'

services:
  db:
    container_name: mysql_db
    image: mysql:8
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./dumps/:/docker-entrypoint-initdb.d/